version: '3'
services:
  api:
    container_name: image-logger
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    user: 'node'
    working_dir: /home/node/src
    environment:
      - HEALTHCHECK_USER_AGENT=image-logger-by-pungrumpy
    healthcheck:
      test:
        - 'CMD'
        - 'curl -H "User-Agent: $HEALTHCHECK_USER_AGENT" -f http://localhost:3000/health || exit 1'
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./src/index.js:/home/node/src/index.js
      - ./src/ipInfo.js:/home/node/src/ipInfo.js
      - ./src/logger.js:/home/node/src/logger.js
      - ./src/server.js:/home/node/src/server.js
      - ./src/webhook.js:/home/node/src/webhook.js
      - ./src/config.json:/home/node/src/config.js
      - ./src/assets:/home/node/src/assets
