version: '3'
services:
  api:
    container_name: image-logger
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/index.js:/home/node/src/index.js
      - ./src/ipInfo.js:/home/node/src/ipInfo.js
      - ./src/logger.js:/home/node/src/logger.js
      - ./src/server.js:/home/node/src/server.js
      - ./src/webhook.js:/home/node/src/webhook.js
      - ./src/config.json:/home/node/src/config.js
      - ./src/assets/*:/home/node/src/assets/
      - ./healthcheck.js:/home/node/healthcheck.js
