version: '3'
services:
  api:
    container_name: image-logger
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json
      - ./config.json:/home/node/config.json
      - ./assets/*:/home/node/assets/*
